@rem
@rem  Gradle start up script for Windows generated by ChatGPT
@rem

@set DIR=%~dp0
@set APP_BASE_NAME=%~n0

@set DEFAULT_JVM_OPTS="-Xmx64m" "-Xms64m"

@set CLASSPATH=%DIR%\gradle\wrapper\gradle-wrapper.jar

@if defined JAVA_HOME (
  @set JAVACMD=%JAVA_HOME%\bin\java.exe
) else (
  @set JAVACMD=java.exe
)

"%JAVACMD%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*
